name: Build and publish
on:
  pull_request:
    types: [closed]
    branches:
      - master
      - develop
      - beta
      - stable
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install NODE JS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install deps
      run: sudo apt update && sudo apt install build-essential && sudo npm install -g node-gyp
    - name: Setup IMA
      run: bash ./scripts/setup_ima.sh
    - name: Build and publish container
      run: |
        export BRANCH=${GITHUB_REF##*/}
        export VERSION=$(cat VERSION)
        echo "Branch: $BRANCH"
        echo "Base version: $VERSION"
        export VERSION=$(bash ./helper-scripts/calculate_version.sh)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version $VERSION"
        export RELEASE=true
        echo "RELEASE=$RELEASE" >> $GITHUB_ENV
        export CONTAINER_NAME="ima_sdk"
        bash ./helper-scripts/build_and_publish.sh
    - name: Checkout code
      uses: actions/checkout@master
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: ${{ env.VERSION }}
        draft: false
        prerelease: true
